version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network_app
    restart: always

  # Redis Cache
  redis:
    image: redis:7.4.0-alpine
    container_name: redis_container
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - network_app
    restart: always

  # Authentication Service
  authentication-service:
    build: ./server/authentication-service
    container_name: authentication-service
    environment:
      PORT: ${AUTHENTICATION_SERVICE_PORT}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - mysql
      - redis
    ports:
      - "${REACT_APP_AUTHENTICATION_SERVICE_PORT}:${AUTHENTICATION_SERVICE_PORT}"
    networks:
      - network_app
    restart: unless-stopped

  # Payment Service
  payment-service:
    build: ./server/payment-service
    container_name: payment-service
    environment:
      PORT: ${PAYMENT_SERVICE_PORT}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - mysql
    ports:
      - "${REACT_APP_PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    networks:
      - network_app
    restart: unless-stopped

  # Common Data Service
  common-data-service:
    build: ./server/common-data-service
    container_name: common-data-service
    environment:
      PORT: ${COMMON_DATA_SERVICE_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: redis://redis:${REDIS_PORT}?password=${REDIS_PASSWORD}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - mysql
      - redis
    ports:
      - "${REACT_APP_COMMON_DATA_SERVICE_PORT}:${COMMON_DATA_SERVICE_PORT}"
    networks:
      - network_app
    restart: unless-stopped

  # Search Suggestion Service
  search-suggestion-service:
    build: ./server/search-suggestion-service
    container_name: search-suggestion-service
    environment:
      PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
      COMMON_DATA_SERVICE_URL: http://common-data-service:${COMMON_DATA_SERVICE_PORT}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - common-data-service
      - mysql
    ports:
      - "${REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT}:${SEARCH_SUGGESTION_SERVICE_PORT}"
    networks:
      - network_app
    restart: unless-stopped

  # React Client
  react-client:
    build:
      context: ./client
      args:
        REACT_APP_PORT: ${REACT_APP_PORT}
        REACT_APP_AUTHENTICATION_SERVICE_URL: ${REACT_APP_AUTHENTICATION_SERVICE_URL}
        REACT_APP_COMMON_DATA_SERVICE_URL: ${REACT_APP_COMMON_DATA_SERVICE_URL}
        REACT_APP_PAYMENT_SERVICE_URL: ${REACT_APP_PAYMENT_SERVICE_URL}
        REACT_APP_SEARCH_SUGGESTION_SERVICE_URL: ${REACT_APP_SEARCH_SUGGESTION_SERVICE_URL}
        REACT_APP_COMMON_DATA_SERVICE_PORT: ${COMMON_DATA_SERVICE_PORT}
        REACT_APP_PAYMENT_SERVICE_PORT: ${PAYMENT_SERVICE_PORT}
        REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
        REACT_APP_AUTHENTICATION_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}

    container_name: react-client
    environment:
      PORT: ${REACT_APP_PORT}
      REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
      REACT_APP_AUTHENTICATION_SERVICE_URL: ${REACT_APP_AUTHENTICATION_SERVICE_URL}
      REACT_APP_COMMON_DATA_SERVICE_URL: ${REACT_APP_COMMON_DATA_SERVICE_URL}
      REACT_APP_PAYMENT_SERVICE_URL: ${REACT_APP_PAYMENT_SERVICE_URL}
      REACT_APP_SEARCH_SUGGESTION_SERVICE_URL: ${REACT_APP_SEARCH_SUGGESTION_SERVICE_URL}
      REACT_APP_COMMON_DATA_SERVICE_PORT: ${COMMON_DATA_SERVICE_PORT}
      REACT_APP_PAYMENT_SERVICE_PORT: ${PAYMENT_SERVICE_PORT}
      REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT: ${SEARCH_SUGGESTION_SERVICE_PORT}
      REACT_APP_AUTHENTICATION_SERVICE_PORT: ${AUTHENTICATION_SERVICE_PORT}
    ports:
      - "${REACT_APP_PORT}:3000"
    depends_on:
      - authentication-service
      - common-data-service
      - search-suggestion-service
      - payment-service
    networks:
        - network_app
    restart: on-failure

# Volumes pour MySQL et Redis
volumes:
  db-data:
  redis-data:

# Utilisation d'un seul réseau pour tous les services
networks:
  network_app:
    driver: bridge